//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FruitServiceClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IFruit")]
    public interface IFruit {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruit/Add", ReplyAction="http://tempuri.org/IFruit/AddResponse")]
        string[] Add(string[] n1, string n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruit/Add", ReplyAction="http://tempuri.org/IFruit/AddResponse")]
        System.Threading.Tasks.Task<string[]> AddAsync(string[] n1, string n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruit/Subtract", ReplyAction="http://tempuri.org/IFruit/SubtractResponse")]
        string[] Subtract(string[] n1, string n2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFruit/Subtract", ReplyAction="http://tempuri.org/IFruit/SubtractResponse")]
        System.Threading.Tasks.Task<string[]> SubtractAsync(string[] n1, string n2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFruitChannel : FruitServiceClient.ServiceReference1.IFruit, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FruitClient : System.ServiceModel.ClientBase<FruitServiceClient.ServiceReference1.IFruit>, FruitServiceClient.ServiceReference1.IFruit {
        
        public FruitClient() {
        }
        
        public FruitClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FruitClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FruitClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FruitClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] Add(string[] n1, string n2) {
            return base.Channel.Add(n1, n2);
        }
        
        public System.Threading.Tasks.Task<string[]> AddAsync(string[] n1, string n2) {
            return base.Channel.AddAsync(n1, n2);
        }
        
        public string[] Subtract(string[] n1, string n2) {
            return base.Channel.Subtract(n1, n2);
        }
        
        public System.Threading.Tasks.Task<string[]> SubtractAsync(string[] n1, string n2) {
            return base.Channel.SubtractAsync(n1, n2);
        }
    }
}
